// app/components/Bubble.tsx
import Image from "next/image";
import React from "react";

function Bubble(props: { link: string; thumbnail: string; color: string }) {
    const { link, thumbnail, color } = props;
    return (
        <a
            className={`flex aspect-square h-[200px] w-[200px] cursor-pointer items-center justify-center overflow-hidden rounded-full border-2 border-zinc-300/90 shadow-md shadow-zinc-400/5 bg-[${color}]`}
            href={link}
        >
            <Image
                className="object-cover"
                src={thumbnail}
                alt="thumbnail"
                width={200}
                height={200}
            />
        </a>
    );
}

export default Bubble;

// components/Bubble/Bubble.vue
<script setup lang="ts">
    import animations from "./animations"

    const props = defineProps<{
        location: {
            row: number
            column: number
            rowLength: number
        }
        title?: string
        path?: string
        penLink?: string
        thumbnail: string
        skills?: string[]
        color?: string
        subtitle?: string
        description?: string
        keywords?: string[]
        hidden?: boolean
        className?: string
    }>()

    const router = useRouter()
    const bubbleRef = ref(null)
    const clicked = ref(false)

    onMounted(() => {
        animations.scroll(
            bubbleRef.value,
            props.location.column,
            props.location.rowLength,
        )
    })

    const handleClick = async () => {
        clicked.value = true
        await animations.expand(bubbleRef.value, props.location)
        router.push(props.path || "/")
    }
</script>

<template>
    <button
        ref="bubbleRef"
        :id="`bubble-${location.row}-${location.column}`"
        :title="title"
        :class="[
            'bubble relative flex aspect-square h-[20vh] max-h-52 cursor-pointer items-center justify-center',
            className,
            hidden ? 'invisible' : '',
        ]"
        @click="handleClick"
        :style="{
            borderRadius: '9999px',
            overflow: clicked ? 'visible' : 'hidden',
            zIndex: clicked ? 100 : 0,
        }"
    >
        <div
            class="bubble-background absolute flex h-full w-full items-center justify-center rounded-full opacity-0"
            :style="{ backgroundColor: color }"
        ></div>

        <div
            v-if="!hidden"
            class="bubble-image relative h-full w-full rounded-full"
        >
            <NuxtImg
                class="h-full w-full rounded-full object-cover"
                :src="thumbnail"
                alt="thumbnail"
            />
        </div>
    </button>
</template>
